version: "3.3"
networks:
  roomler_proxy:
    external: true
  roomler_db:
    external: true
    roomler_redis:
      external: true

services:
  nginx:
    image: nginx:alpine
    networks:
      - roomler_proxy
    volumes:
      - /path_to_nginx.conf:/etc/nginx/nginx.conf
      - /path_to_conf.d/:/etc/nginx/conf.d/
      - /path_to_cert/:/etc/nginx/cert/
      - /path_to_logs/:/etc/nginx/logs/
    ports:
      - "80:80"
      - "443:443"

  redis:
    image: bitnami/redis:latest
    networks:
      - roomler_redis
    volumes:
      - /gjovanov/db/:/data/db
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica == redis

  mongo:
    image: gjovanov/janus:0.1.3
    networks:
      - roomler_db
    volumes:
      - /gjovanov/db/:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo_user
      - MONGO_INITDB_ROOT_PASSWORD=mongo_password
    ports:
      - "1213:27017"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica == mongo

  coturn:
    image: gjovanov/coturn:0.1.2
    networks:
      - host
      - roomler_db
    command: >
      -n
      --log-file=stdout
      --min-port=49152
      --max-port=65535
      --listening-ip=your_public_ip
      --relay-ip=your_public_ip
      --lt-cred-mech
      --fingerprint
      --mongo-userdb="mongodb://mongo_user:mongo_password@mongo:1312/coturn"
      --no-multicast-peers
      --no-cli
      --no-tlsv1
      --no-tlsv1_1
      --realm=your_realm
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica == coturn

  janus:
    image: gjovanov/janus:0.1.3
    networks:
      - roomler_proxy
    volumes:
      - /cert_path.pem:/usr/local/nginx/server.crt
      - /key_path.key:/usr/local/nginx/server.key
      - /log_janus:/app/log
    ports:
      - "81:80"
      - "444:443"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica == janus

  roomler:
    image: gjovanov/roomler
    networks:
      - roomler_proxy
      - roomler_db
      - roomler_redis
    volumes:
      - /path_to_uploads:/roomler/ui/static/uploads
    environment:
      - URL=https://roomler.live
      - API_URL=https://roomler.live
      - DB_CONN=mongodb://mongo_user:mongo_password@mongo:1312/roomlerdb
      - WS_SCALEOUT_ENABLED=true
      - WS_SCALEOUT_HOST=redis
      - SENDGRID_API_KEY=your_sendgrid_api_key
      - FACEBOOK_ID=your_facebook_id
      - FACEBOOK_SECRET=your_facebook_secret
      - GOOGLE_ID=your_google_id
      - GOOGLE_SECRET=your_google_secret
      - GITHUB_ID=your_github_id
      - GITHUB_SECRET=your_github_secret
      - LINKEDIN_ID=your_linkedin_id
      - LINKEDIN_SECRET=your_linkedin_secret
      - TURN_URL=turn:your_turn_server:3478?transport=tcp
      - TURN_USERNAME=turn_user
      - TURN_PASSWORD=turn_password
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica == roomler
